server:
  port: ${PORT:31001}
spring:
  rabbitmq:
    host: codeyaa.com
    port: 5672
    username: guest
    password: cn.mq183
    virtualHost: /
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@ymy.codeyaa.com:27017
      database: xc_cms
  freemarker:
    cache: false # 关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 # 检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/}
  instance:
    prefer-ip-address: true  # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定实例id