server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:root@codeyaa.com:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: codeyaa.com
    port: 5672
    username: guest
    password: cn.mq183
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: C:/Users/funtion/IdeaProjects/xczx-ui/media
  ffmpeg-path: C:\Program Files\Java\ffmpeg-20180227-fa0c9d6-win64-static\bin\ffmpeg.exe